Release v1.3/overzichtspag vereisten maatregelen
MinBZK/Algoritmekader pull request #151
Opened 2024-06-17 06:49 UTC by ruthkoole

## Beschrijf jouw aanpassingen
Nieuwe overzichtspagina's voor vereisten en maatregelen

## Bij welk issue hoort deze pull-request?
#140 

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader. 
- [ ] Deze pull-request gaat naar de juiste branch (in principe mergen we eerst naar de branch `release` alvorens te mergen naar de `main` branch).

2024-06-24 19:39 UTC, ruthkoole commented
voor een volgende keer moeten we nog kijken naar de volgorde van de vereisten. Wordt nu bepaald op basis van bestandsnaam. Dat is niet ideaal.

2024-06-25 11:46 UTC, noutvandeijck requested changes
Kleine wijzigingen zoals gefixte links en taalfoutje.

2024-06-25 11:46 UTC, noutvandeijck commented on docs/vereisten/index.md
> +Onderstand volgt een overzicht van maatregelen per fase van de levenscyclus.
```suggestion
Onderstand volgt een overzicht van vereisten per fase van de levenscyclus. 
```

2024-07-01 10:48 UTC, BartdeVisser commented on docs/maatregelen/archiveren_vaststellen_documenten.md
> +|[Toetsingskader Algemene Rekenkamer 4.06](https://www.rekenkamer.nl/onderwerpen/algoritmes/documenten/publicaties/2024/05/15/het-toetsingskader-aan-de-slag)|
Goed punt, ik zie hem nu ook niet meer logisch overlappen. Misschien dat het in de vorige versie van het Toetsingskader beter aansloot. Ik haal het er nu uit omdat ik het onvoldoende zie terugkomen in het Toetsingskader.

2024-07-01 10:48 UTC, BartdeVisser commented on docs/maatregelen/archiveren_vaststellen_documenten.md
> +|[Toetsingskader Algemene Rekenkamer 4.06](https://www.rekenkamer.nl/onderwerpen/algoritmes/documenten/publicaties/2024/05/15/het-toetsingskader-aan-de-slag)|
```suggestion
| Algoritmekader |
```

2024-07-02 08:44 UTC, noutvandeijck approved these changes

2024-07-02 09:41 UTC, merged