toevoegen nieuwe maatregelen release v1.3
MinBZK/Algoritmekader pull request #163
Opened 2024-06-28 12:09 UTC by ruthkoole

## Beschrijf jouw aanpassingen

## Bij welk issue hoort deze pull-request?

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader. 
- [ ] Deze pull-request gaat naar de juiste branch (in principe mergen we eerst naar de branch `release` alvorens te mergen naar de `main` branch).

2024-06-28 13:30 UTC, ruthkoole commented on docs/vereisten/beperkte_bewaartermijn_van_persoonsgegevens.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:30 UTC, ruthkoole commented on docs/vereisten/databankenwet.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:30 UTC, ruthkoole commented on docs/vereisten/fundamentele_rechten.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:30 UTC, ruthkoole commented on docs/vereisten/inroepen_privacyrecht_bij_verwerking_persoonsgegevens.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:31 UTC, ruthkoole commented on docs/vereisten/juistheid_en_actualiteit_van_persoonsgegevens.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:31 UTC, ruthkoole commented on docs/vereisten/minimale_verwerking_van_persoonsgegevens.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:31 UTC, ruthkoole commented on docs/vereisten/persoonsgegevens_worden_rechtmatig_verwerkt.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:31 UTC, ruthkoole commented on docs/vereisten/privacy_bij_ontwerp_bij_verwerking_van_persoonsgegevens.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:31 UTC, ruthkoole commented on docs/vereisten/recht_op_toegang_tot_publieke_informatie.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:31 UTC, ruthkoole commented on docs/vereisten/risicobeoordeling_voor_jongeren_en_kwetsbaren.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:31 UTC, ruthkoole commented on docs/vereisten/transparantie_bij_verwerken_persoonsgegevens.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:32 UTC, ruthkoole commented on docs/vereisten/transparantie_bij_verwerken_persoonsgegevens.md
> +
```suggestion
```

2024-06-28 13:32 UTC, ruthkoole commented on docs/vereisten/verdere_verwerking_van_persoonsgegevens_in_ai_testomgevingen.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:32 UTC, ruthkoole commented on docs/vereisten/verplichtingen_van_aanbieders_van_ai_modellen_voor_algemene_doeleinden.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:32 UTC, ruthkoole commented on docs/vereisten/verplichtingen_van_aanbieders_van_ai_modellen_voor_algemene_doeleinden_met_systeemrisico.md
> +---
```suggestion
hide:
- navigation
---
```

2024-06-28 13:32 UTC, ruthkoole commented on docs/vereisten/wettelijke_verwerking_van_gevoelige_gegevens.md
> +---
```suggestion
hide:
- navigation
---
```

2024-07-01 09:05 UTC, BartdeVisser commented on docs/vereisten/verplichtingen_van_aanbieders_van_ai_modellen_voor_algemene_doeleinden.md
> +Dit vraagt om om een goed inzicht in de modellen en hun capaciteiten, zowel qua integratie van de modellen in hun producten als qua naleving van hun verplichtingen.
```suggestion
Dit vraagt om een goed inzicht in de modellen en hun capaciteiten, zowel qua integratie van de modellen in hun producten als qua naleving van hun verplichtingen.
```

2024-07-01 09:05 UTC, BartdeVisser commented on docs/vereisten/verplichtingen_van_aanbieders_van_ai_modellen_voor_algemene_doeleinden_met_systeemrisico.md
> +Systeemrisico betekent: een risico dat specifiek is voor de capaciteiten met een grote impact van AI-modellen voor algemene doeleienden, die aanzienlijke gevolgen hebben voor de markt van de Uniek va
```suggestion
Systeemrisico betekent: een risico dat specifiek is voor de capaciteiten met een grote impact van AI-modellen voor algemene doeleienden, die aanzienlijke gevolgen hebben voor de markt van de Uniek vanwege hun bereik, of vanwege feitelijke of redelijkerwijs te voorziene negatieve gevolgen voor de gezondheid, de veiligheid, de openbare veiligheid, de grondrechten of de samenleving als geheel, en dat op grote schaal in de hele waardeketen kan worden verspreid.
```

2024-07-01 09:05 UTC, BartdeVisser commented on docs/vereisten/wettelijke_verwerking_van_gevoelige_gegevens.md
> +title: Wettelijke uitzondering nodig voor verwerken bijzondere categoriën persoonsgegevens
```suggestion
title: Wettelijke uitzondering nodig voor verwerken bijzondere categorieën persoonsgegevens
```

2024-07-01 09:05 UTC, BartdeVisser commented on docs/vereisten/wettelijke_verwerking_van_gevoelige_gegevens.md
> +toelichting: Bijzondere categoriën van persoonsgegevens mogen alleen worden verwerkt op basis van een wettelijke uitzondering.
```suggestion
toelichting: Bijzondere categorieën van persoonsgegevens mogen alleen worden verwerkt op basis van een wettelijke uitzondering.
```

2024-07-01 09:05 UTC, BartdeVisser commented on docs/vereisten/wettelijke_verwerking_van_gevoelige_gegevens.md
> +Bijzondere categoriën van persoonsgegevens mogen alleen worden verwerkt op basis van een wettelijke uitzondering.
```suggestion
Bijzondere categorieën van persoonsgegevens mogen alleen worden verwerkt op basis van een wettelijke uitzondering.
```

2024-07-01 09:05 UTC, BartdeVisser commented on docs/vereisten/wettelijke_verwerking_van_gevoelige_gegevens.md
> +Bijzondere categoriën persoonsgegevens mogen alleen worden verwerkt als er hier een wettelijke uitzondering voor is (art.
```suggestion
Bijzondere categorieën persoonsgegevens mogen alleen worden verwerkt als er hier een wettelijke uitzondering voor is (art.
```

2024-07-01 09:05 UTC, BartdeVisser commented on docs/vereisten/wettelijke_verwerking_van_gevoelige_gegevens.md
> +Deze vereiste is ook van toepassing bij het ontwikkelen en gebruiken van algoritmes of AI-systemen en stelt daarmee beperkingen aan het mogen verwerken van deze categoriën persoonsgegevens, bv.
```suggestion
Deze vereiste is ook van toepassing bij het ontwikkelen en gebruiken van algoritmes of AI-systemen en stelt daarmee beperkingen aan het mogen verwerken van deze categorieën persoonsgegevens, bv.
```

2024-07-01 09:05 UTC, BartdeVisser commented on docs/vereisten/wettelijke_verwerking_van_gevoelige_gegevens.md
> +Het (onrechtmatige) verwerken van bijzondere categoriën persoonsgegevens brengt risico's met zich mee op het gebied van respecteren van de persoonlijke levenssfeer en discriminatie.
```suggestion
Het (onrechtmatige) verwerken van bijzondere categorieën persoonsgegevens brengt risico's met zich mee op het gebied van respecteren van de persoonlijke levenssfeer en discriminatie.
```

2024-07-02 07:29 UTC, noutvandeijck requested changes
Vooral tekstuele aanpassingen of voorstellen. Paar vereisten die erg complex of letterlijk vertaald zijn opgeschreven, waar we misschien eens samen met onze content specialist uitgebreider voor moeten zitten..

2024-07-02 07:29 UTC, noutvandeijck commented on docs/vereisten/verplichtingen_van_aanbieders_van_ai_modellen_voor_algemene_doeleinden.md
> +Dit vraagt om een goed inzicht in de modellen en hun capaciteiten, zowel qua integratie van de modellen in hun producten als qua naleving van hun verplichtingen.
Deze zinnen lezen een beetje verwarrend. Ook weet ik niet of bij iedereen de term AI-waardeketen bekend is. Dit is een vaag begrip en kunnen we denk ik concreter opschrijven. Misschien iets als:

```suggestion
Aanbieders van AI-modellen voor algemene doeleinden hebben een bijzondere rol en verantwoordelijkheid.
Zij leveren modellen die de basis kunnen vormen voor weer andere systemen en algoritmen, die vaak weer door andere partijen worden aangeboden dan de ontwikkelaar van het algemene systeem.
Dit vraagt om een goed inzicht in de modellen en hun capaciteiten, zowel qua integratie van de modellen in producten als qua naleving van verplichtingen.
```

2024-07-02 07:29 UTC, noutvandeijck commented on docs/vereisten/verplichtingen_van_aanbieders_van_ai_modellen_voor_algemene_doeleinden.md
> +Er zijn daarom evenredige transparantiemaatregelen nodig, zoals opstelling en bijwerking van documentatie en verstrekking van informatie over het AI-model voor algemeen gebruik door de aanbieders ver
```suggestion
Er zijn daarom evenredige transparantiemaatregelen nodig, zoals het opstellen en bijwerken van documentatie en verstrekken van informatie over het AI-model voor algemeen gebruik door de aanbieders van systemen die de algemene modellen gebruiken in hun product.
```

2024-07-02 07:29 UTC, noutvandeijck commented on docs/vereisten/verplichtingen_van_aanbieders_van_ai_modellen_voor_algemene_doeleinden.md
> +De aanbieder van het AI-model voor algemene doeleinden dient technische documentatie op te stellen en bij te werken om deze op verzoek te kunnen overleggen aan het AI-bureau en de nationale bevoegde
Wordt met AI-bureau hier het AI-office bedoelt wat er vanuit de EU gaat komen? Is dat al een gangbare Nederlandse term, en willen we daar al naar verwijzen?

2024-07-02 07:29 UTC, noutvandeijck commented on docs/vereisten/verplichtingen_van_aanbieders_van_ai_modellen_voor_algemene_doeleinden_met_systeemrisico.md
> +Systeemrisico’s nemen logischerwijs toe naargelang de capaciteiten en het bereik van een model groter zijn, kunnen zich voordoen gedurende de gehele levenscyclus van het model en worden beïnvloed doo
```suggestion
Systeemrisico’s nemen logischerwijs toe naargelang de capaciteiten en het bereik van een model groter zijn, kunnen zich voordoen gedurende de gehele levenscyclus van het model en worden beïnvloed door elementen als misbruik van het model, de betrouwbaarheid, billijkheid, beveiliging en mate van autonomie ervan. Ook worden ze beïnvloed door de toegang van het model tot instrumenten, nieuwe of gecombineerde modaliteiten, introductie- en distributiestrategieën, en door het potentieel om waarborgen te omzeilen en andere factoren.
```
leesbaarheid iets aangepast. Maar ik denk dat dit nog steeds erg complex is opgeschreven allemaal. Misschien keer samen met onze content specialist naar kijken!

2024-07-02 09:13 UTC, noutvandeijck approved these changes
Paar keer op leesbaarheid suggesties gedaan, en ik denk dat er nog 1 of enkele te complex zijn opgeschreven. Maar daar gaat onze content specialist nog een keer overheen later.

Dus voor nu goed! Misschien kunnen mijn suggestions nog gecommit worden en daardoor worden meegenomen! ;)

2024-07-02 13:23 UTC, merged