Create vaststellen_verantwoordelijkheden.md
MinBZK/Algoritmekader pull request #179
Opened 2024-07-15 07:16 UTC by BartdeVisser

## Beschrijf jouw aanpassingen

## Bij welk issue hoort deze pull-request?

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader. 
- [ ] Deze pull-request gaat naar de juiste branch (in principe mergen we eerst naar de branch `release` alvorens te mergen naar de `main` branch).

2024-07-15 07:26 UTC, floort commented
Ik lees in het voorstel dat een ongespecificeerde partij *toewijst* wie wie de verwerkingsverantwoordelijke is.
> Nadat de verantwoordelijkheden zijn beschreven en toegewezen, zullen deze moeten worden vastgesteld door de verwerkersverantwoordelijke.  

Dat is niet hoe de AVG werkt. Onder de AVG moet aan de hand van de feitelijke situatie worden vastgesteld wie er feitelijk doel en middelen (mede) bepalen. Zie bijvoorbeeld: https://www.edpb.europa.eu/our-work-tools/documents/public-consultations/2020/guidelines-072020-concepts-controller-and_en

> Nadat is vastgesteld wie in een samenwerking feitelijk het doel en middelen van een verwerking bepalen wordt vastgelegd wie de (gezamelijke) verwerkingsverantwoordelijken zijn en wie de verwerkers. Uit deze vaststeling van de rolverdeling volgen onder de AVG verschillende rechten en plichten.

2024-07-15 09:06 UTC, floort commented
Het uitvoeren van een DPIA is geen onderdeel van het vaststellen van verantwoordelijkheiden. Het in kaart brengen van de verschillende rollen en diens belangen is wel onderdeel van de DPIA onder artikel 35(7)(a) AVG.  Commit  de30297 hoort denk ik niet thuis in deze PR.

Inhoudelijk missen er enkele belangrijke onderdelen. Zo mist er bijvoorbeeld dat [volgens de AP](https://www.autoriteitpersoonsgegevens.nl/documenten/lijst-verplichte-dpia) een DPIA in ieder geval moet worden uitgevoerd als er sprake is van één van de volgende elementen:
1. Evaluatie of scoretoekenning
2. Geautomatiseerde besluitvorming met rechtsgevolg of vergelijkbaar wezenlijk gevolg
3. Stelselmatige monitoring
4. Gevoelige gegevens of gegevens van zeer persoonlijke aard
5. Op grote schaal verwerkte gegevens
6. Matching of samenvoeging van datasets
7. Gegevens met betrekking tot kwetsbare betrokkenen
8. Innovatief gebruik of innovatieve toepassing van nieuwe technologische of organisatorische
oplossingen
9. de situatie waarin als gevolg van de verwerking zelf ″betrokkenen [...] een recht niet kunnen
uitoefenen of geen beroep kunnen doen op een dienst of een overeenkomst″;

Ook is het belangrijk om te benoemen dat bij hoge risico's een voorafgaande raadpeging bij de AP onder aritkel 36 AVG verplicht is. Het monitoren van de voortgang van de maatregelen zoals gesuggereerd wordt is niet altijd een verplichting. Als het gaat om maatregelen voor hoge risico's mag de verwerking niet starten zonder voorafgaande raadpleging. En als de verwerking nog niet gestart is zijn er onder de AVG geen verplichtingen om maatregelen te monitoren en vast te leggen. Ik denk dat het helpt om artikel 36 op te nemen in de omschrijving.

2024-08-06 13:28 UTC, noutvandeijck requested changes
Supermooie maatregelen! Heb heel wat commits, suggestions en comments gedaan.

Commits om alle errors op gebied van tagging te fixen, suggestions vooral voor tekstuele of taaldingen, paar inhoudelijk. Comments hier en daar omdat ik een vraag had, of wanneer ik denk dat er overlap was tussen maatregelen. Suggestions kunnen als het goed is direct gecommit worden (mits je het ermee eens bent). Comments kun je misschien nog naar kijken.

Overall werd ik echt super blij van al deze maatregelen, heel mooie toevoegingen!!

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/toepassen_risicobeheer.md
> +- Daarbij gaat het om het identificeren, analyseren, evalueren (tav risk apetite), behandelen (risicoreactie, o.a. maatregelen), monitoren & beoordelen en communiceren & rapporteren van risico's.
```suggestion
- Daarbij gaat het om het identificeren, analyseren, evalueren (afhankelijk van de risicobereidheid), behandelen (risicoreactie, o.a. maatregelen), monitoren & beoordelen en communiceren & rapporteren van risico's.
```
Even vertaald. Klopt dit zo?

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/toepassen_risicobeheer.md
> +vereiste:
Moet deze maatregelen aan zóveel vereisten worden gekoppeld?

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/uitvoeren_risicoanalyse_en_formuleren_mitigerende_maatregelen_voor_privacyrisico's.md
> +Uitvoeren DPIA en formuleren mitigerende maatregelen.
```suggestion
Uitvoeren van een [DPIA](../instrumenten/DPIA.md) en formuleren van mitigerende maatregelen. 
```
interne link gelegd

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/uitvoeren_risicoanalyse_en_formuleren_mitigerende_maatregelen_voor_privacyrisico's.md
> +- Verifieer of een DPIA over het werkproces is uitgevoerd dat wordt of zal worden ondersteund met een algoritme of AI-systeem.
```suggestion
- Verifieer of een DPIA is uitgevoerd over het werkproces dat wordt of zal worden ondersteund met een algoritme of AI-systeem.
```

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/uitvoeren_risicoanalyse_en_formuleren_mitigerende_maatregelen_voor_privacyrisico's.md
> +- Als er een noodzaak is om na verloop van tijd meer persoonsgegevens te werken of om andere verwerkingen uit te voeren, zal opnieuw een beoordeling moeten plaatsvinden of er privacyrisico's ontstaan
```suggestion
- Als er een noodzaak is om na verloop van tijd meer persoonsgegevens te verwerken of om andere verwerkingen uit te voeren, zal opnieuw een beoordeling moeten plaatsvinden of er privacyrisico's ontstaan en hoe deze kunnen worden gemitigeerd. Gedurende de levenscyclus van het algoritme of AI-systeem moet aandacht blijven voor het uitvoeren van de risicoanalyse voor privacyrisico's.
```

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vaststellen_rollen_en_verantwoordelijkheden.md
> +zorgvuldigheidsbeginsel
```suggestion
```

Dit wordt automatisch al ingevuld obv de tagging!

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vaststellen_rollen_en_verantwoordelijkheden.md
Veel overlap met de maatregel 'stel_een_RACI-matrix_op.md'. Kunnen die worden samengevoegd denk je? Zo niet, misschien op relevante punten naar elkaar laten verwijzen?

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vaststellen_verantwoordelijkheden_persoonsgegevens.md
> +verantwoordingsplicht_rechtmatigheid
```suggestion
```
Hoort de maatregel bij deze vereisten? Dan moet dat bovenaan bij de tagging zo worden ingevuld. Heb ze als suggestie daar nu toegevoegd.

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vaststellen_verantwoordelijkheden_persoonsgegevens.md
> +- beschrijven_en_toewijzen_van_verantwoordelijkheden_bij_verwerking_persoonsgegevens
```suggestion
vereiste:
- beschrijven_en_toewijzen_van_verantwoordelijkheden_bij_verwerking_persoonsgegevens
- dpia_verplicht_bij_hoog_risico
- transparantie_bij_verwerken_persoonsgegevens
- zorgvuldigheidsbeginsel
- verantwoordingsplicht_rechtmatigheid
```

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vermelding_in_privacyverklaring.md
> +title: Neem de ontwikkeling en gebruik van een algoritme of AI-systeem op in een privacyverklaring als persoonsgegevens worden verwerkt.
```suggestion
title: Neem het gebruik van een algoritme of AI-systeem op in een privacyverklaring als persoonsgegevens worden verwerkt. 
```

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vermelding_in_privacyverklaring.md
> + Neem de ontwikkeling en gebruik van een algoritme of AI-systeem op in de privacyverklaring als hierbij persoonsgegevens worden verwerkt.
```suggestion
 Neem het gebruik van een algoritme of AI-systeem op in de privacyverklaring als hierbij persoonsgegevens worden verwerkt.  
```

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vermelding_in_privacyverklaring.md
> +- Privacyverklaring kunnen op organistieniveau worden opgesteld en ook voor specifieke situaties.
```suggestion
- Een privacyverklaring kan op organistieniveau worden opgesteld en ook voor specifieke situaties.
```

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vermelding_in_privacyverklaring.md
> +Betrokkenen zijn niet op de hoogte dat hun persoonsgegevens worden verwerkt met een algoritme of AI-systeem, waardoor zij hier geen controle over hebben.
```suggestion
Betrokkenen zijn niet op de hoogte dat hun persoonsgegevens worden verwerkt met een algoritme of AI-systeem, waardoor zij hier geen controle over hebben., en zich niet goed kunnen beroepen op hun privacyrechten.
```

2024-08-06 13:28 UTC, noutvandeijck commented on docs/maatregelen/vertaling_wetgeving_beleid_naar_werkproces_systemen.md
Superbelangrijke maatregel. Mooi beschreven!!

2024-08-06 14:21 UTC, noutvandeijck commented on docs/maatregelen/benodigde expertise_en_capaciteit.md
> +- [Interne en externe actoren die betrokken zijn bij het ontwikkelen](/betrek_belanghebbenden), inkopen en gebruik moeten over voldoende expertise en capaciteit beschikken om hun taken naar behoren u
```suggestion
- [Interne en externe actoren die betrokken zijn bij het ontwikkelen](/betrek_belanghebbenden.md), inkopen en gebruik moeten over voldoende expertise en capaciteit beschikken om hun taken naar behoren uit te voeren.
```

2024-08-06 15:27 UTC, ruthkoole commented on src/overrides/hooks/lists.py
> +
```suggestion
```

2024-08-07 11:53 UTC, BartdeVisser reviewed
@noutvandeijck, zie dat je hier de architect eruit hebt gehaald? Is dat bewust? Meestal is deze expert wel onderdeel van deze werkzaamheden

2024-08-07 11:53 UTC, BartdeVisser commented on docs/maatregelen/vaststellen_rollen_en_verantwoordelijkheden.md
Goed punt, ben ondertussen verder gegaan met werken in deze branche en heb toevallig de maatregel 'Stel RACI matrix op' eruit gehaald en hier verwerkt: https://github.com/MinBZK/Algoritmekader/blob/Release-1.4-toevoegen-maatregelen/docs/maatregelen/beschrijf_rollen_en_verantwoordelijkheden.md

2024-08-14 08:21 UTC, noutvandeijck approved these changes

2024-08-14 08:22 UTC, merged