Release v1.4/algoritmekader home tekst en opmaak
MinBZK/Algoritmekader pull request #192
Opened 2024-08-01 11:07 UTC by webredactie-algoritmekader

## Beschrijf jouw aanpassingen

- Aangepaste tekst en opmaak: o.a. eenvoudiger en beter scanbaar.
- De harde kern staat nu onder 'Voldoen aan de regels'. De rest staat onder 'Onderwerpen' en 'Rollen'.
- Qua opmaak kan dit natuurlijk een stuk funkyer. Misschien kan Ruben hier nog iets mee?

## Bij welk issue hoort deze pull-request?
Kan ik nu niet opzoeken door IT-probleem ICTU
## Checklist before requesting a review
- [x ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [x ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [x ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [x ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader. 
- [x ] Deze pull-request gaat naar de juiste branch (in principe mergen we eerst naar de branch `release` alvorens te mergen naar de `main` branch).

2024-08-01 14:55 UTC, webredactie-algoritmekader commented
@rubenrouwhof: Kun jij nog je visual magic toevoegen? :)

2024-08-06 15:30 UTC, ruthkoole commented
ZIet er al goed uit! Nog wat opmerkingen en suggesties gedaan. Wordt zo denk ik wel een stuk leesbaarder. Voordat we gaan mergen, lijkt het me wel nog goed als we het qua layout nog iets aantrekkelijker maken? Onderstaand ziet er nog wat kaal uit mijns inziens. Kan @rubenrouwhof ons misschien mee helpen? :)

![afbeelding](https://github.com/user-attachments/assets/b1177bb8-f400-4ea3-8827-cb4f27b04caa)

2024-08-07 07:09 UTC, ruthkoole requested changes

2024-08-08 13:48 UTC, webredactie-algoritmekader commented on docs/index.md
> +summary: In het Algoritmekader staan alle regels, tips en hulpmiddelen voor overheden voor verantwoord gebruik van algoritmes en AI.
```suggestion
summary: In het Algoritmekader staan de wetten en regels, tips en hulpmiddelen voor overheden voor verantwoord gebruik van algoritmes en AI. 
```

2024-08-08 13:57 UTC, webredactie-algoritmekader commented on docs/index.md
> +Alle regels, tips en hulpmiddelen voor verantwoord gebruik van algoritmes en AI.
```suggestion
Wetten en regels, tips en hulpmiddelen voor verantwoord gebruik van algoritmes en AI door de overheid.
```

2024-08-08 13:59 UTC, webredactie-algoritmekader commented on docs/index.md
> +Alle regels, tips en hulpmiddelen voor verantwoord gebruik van algoritmes en AI.
"Wetten en regels" van gemaakt.

2024-08-08 14:02 UTC, webredactie-algoritmekader commented on docs/index.md
> +## Versie 1.4
```suggestion
## Testversie
```

2024-08-08 14:07 UTC, webredactie-algoritmekader commented on docs/index.md
> +## Versie 1.4
```suggestion
## Beta-versie
```

2024-08-09 16:06 UTC, webredactie-algoritmekader commented on docs/index.md
> +## Versie 1.4
```suggestion
## Bètaversie
```

2024-08-09 16:10 UTC, webredactie-algoritmekader commented on docs/index.md
> +Deze website is een testversie. Alle versies ontstaan op een open manier. Iedereen mag [opmerkingen of suggesties](https://minbzk.github.io/Algoritmekader/overhetalgoritmekader/CONTRIBUTING/) geven.
```suggestion
Deze website is nog in ontwikkeling, het is een bètaversie. Alle versies ontstaan op een open manier. Iedereen mag [opmerkingen of suggesties](https://minbzk.github.io/Algoritmekader/overhetalgoritmekader/CONTRIBUTING/) geven.
```

2024-08-09 16:19 UTC, webredactie-algoritmekader commented on docs/index.md
> +- [Eisen](https://minbzk.github.io/Algoritmekader/vereisten/)
Ik koos 'eis' omdat dit een begrijpelijker woord is, zie https://ishetb1.nl/search?word=vereiste. En ik vraag me af of het verschil tussen eisen en vereisten duidelijk is voor de gemiddelde lezer . Toezichthouder ACM gebruikt in elk geval gewoon 'eisen', zie bv. https://www.acm.nl/nl/energie/elektriciteit-en-gas/energie-verkopen/energie-leveren-met-vergunning/eisen-energievergunning. @BartdeVisser: Durf je het aan met 'eisen'? :)

2024-08-09 16:22 UTC, webredactie-algoritmekader commented on docs/index.md
> +- [Grondrechten](https://minbzk.github.io/Algoritmekader/bouwblokken/fundamentele-rechten/)
Grondrechten zou dezelfde betekenis hebben als 'fundamentele rechten', zie [Grondrechten - Wikipedia](https://nl.wikipedia.org/wiki/Grondrechten). En grondrechten is als term veel bekender in Nederland. Mensen zoeken nauwelijks op "fundamentele rechten", zie [grondrechten, fundamentele rechten, mensenrechten - Verkennen - Google Trends](https://trends.google.com/trends/explore?date=today%205-y&geo=NL&q=grondrechten,fundamentele%20rechten,mensenrechten&hl=nl). @BartdeVisser: Kun je je vinden in 'Grondrechten' i.p.v. 'Fundamentele rechten'?

2024-08-09 16:24 UTC, webredactie-algoritmekader commented on docs/index.md
> +- [Levenscyclus van algoritmes en AI](https://minbzk.github.io/Algoritmekader/levenscyclus/)
```suggestion
```

2024-08-09 16:27 UTC, webredactie-algoritmekader commented on docs/index.md
> +- [Levenscyclus van algoritmes en AI](https://minbzk.github.io/Algoritmekader/levenscyclus/)
Prima., ik laat 'Levenscyclus' er wel uit. We gaan sowieso nog gebruikersonderzoek doen naar de indeling van de navigatiebalk.

2024-08-09 16:28 UTC, webredactie-algoritmekader commented on docs/index.md
> +- [Security-officers](https://minbzk.github.io/Algoritmekader/rollen/security-officer/)
Prima. Ik weet zelf niet hoe, dus ik doe met dit punt even niks :)

2024-08-09 16:30 UTC, webredactie-algoritmekader reviewed
Volgens mij heb ik alle opmerkingen verwerkt. Hoop dat ik het goed heb gedaan zo.

2024-08-12 16:07 UTC, ruthkoole commented on docs/index.md
> +Alle regels, tips en hulpmiddelen voor verantwoord gebruik van algoritmes en AI.
```suggestion
Wetten en regels, tips en hulpmiddelen voor verantwoord gebruik van algoritmes en AI.
```

2024-08-13 14:29 UTC, ruthkoole commented
Deze PR komt te vervallen door PR #219

2024-08-13 14:29 UTC, closed without merging