Update index.md
MinBZK/Algoritmekader pull request #202
Opened 2024-08-01 12:35 UTC by webredactie-algoritmekader

Aangepaste tekst en opmaak: eenvoudiger en beter scanbaar. Plaatjes weggelaten, maar hierdoor zagen de blokjes er gek uit. Blokjes daarom ook maar weggelaten. Eventueel opmaak in blokjes, zonder plaatjes. Misschien heeft Ruben een goed idee?

## Beschrijf jouw aanpassingen
Zie hierboven.
## Bij welk issue hoort deze pull-request?
Kan ik nu niet opzoeken door IT-probleem ICTU.
## Checklist before requesting a review
- [x] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [x] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [x] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [x] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader. 
- [x] Deze pull-request gaat naar de juiste branch (in principe mergen we eerst naar de branch `release` alvorens te mergen naar de `main` branch).

2024-08-01 14:33 UTC, webredactie-algoritmekader commented
@rubenrouwhof: Ga gerust los met opmaak :)

2024-08-07 11:26 UTC, ruthkoole requested changes

2024-08-07 11:26 UTC, ruthkoole commented on docs/bouwblokken/index.md
> +    Hulp bij het voorkomen van bias en discriminatie in algoritmes en AI. Met aanbevelingen en hulpmiddelen zoals het Fairness Handbook.
```suggestion
    Hulp bij het voorkomen van bias en discriminatie in algoritmes en AI. Met aanbevelingen en hulpmiddelen zoals het toetsingskader van het College voor de Rechten van de Mens
```

2024-08-07 11:26 UTC, ruthkoole commented on docs/bouwblokken/index.md
>  title: Bouwblokken
```suggestion
title: Bouwblokken
```

2024-08-07 11:27 UTC, ruthkoole commented
Eens om bouwblok te hernoemen naar onderwerp. Die wijziging moeten we dan wel consistent doorvoeren (ook in de naamgeving van de onderliggende mappen).

2024-08-09 16:39 UTC, webredactie-algoritmekader commented on docs/bouwblokken/index.md
>  title: Bouwblokken
```suggestion
title: Onderwerpen
```

2024-08-09 16:40 UTC, webredactie-algoritmekader commented on docs/bouwblokken/index.md
> +    Hulp bij het voorkomen van bias en discriminatie in algoritmes en AI. Met aanbevelingen en hulpmiddelen zoals het Fairness Handbook.
```suggestion
    Hulp bij het voorkomen van bias en discriminatie in algoritmes en AI. Met aanbevelingen en hulpmiddelen zoals het toetsingskader van het College voor de Rechten van de Mens.
```

2024-08-09 16:41 UTC, webredactie-algoritmekader commented on docs/bouwblokken/index.md
> +    Hulp bij het voorkomen van bias en discriminatie in algoritmes en AI. Met aanbevelingen en hulpmiddelen zoals het Fairness Handbook.
Eens, maar er ontbrak nog een punt :)

2024-08-09 16:42 UTC, webredactie-algoritmekader reviewed
Nog dingetjes: Title = ook Onderwerpen? En een punt achter jouw suggestie.

2024-08-12 16:47 UTC, ruthkoole commented on docs/bouwblokken/index.md
> +-   [Grondrechten](fundamentele-rechten/index.md)
```suggestion
-   [Fundamentele rechten](fundamentele-rechten/index.md)
```

2024-08-12 16:47 UTC, ruthkoole commented on docs/bouwblokken/index.md
> +-   [Governance](governance/index.md)
```suggestion
-   [Governance](../governance/index.md)
```

2024-08-13 05:14 UTC, merged