release-v1.4/publieke-inkoop-tekst-en-opmaak
MinBZK/Algoritmekader pull request #210
Opened 2024-08-08 11:46 UTC by webredactie-algoritmekader

## Beschrijf jouw aanpassingen

## Bij welk issue hoort deze pull-request?

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader. 
- [ ] Deze pull-request gaat naar de juiste branch (in principe mergen we eerst naar de branch `release` alvorens te mergen naar de `main` branch).

2024-08-09 06:39 UTC, webredactie-algoritmekader commented
@ruthkoole: De preview-link werkt niet (die met dat raketje). Weet jij misschien hoe dat komt?

2024-08-09 07:35 UTC, ruthkoole commented
> @ruthkoole: De preview-link werkt niet (die met dat raketje). Weet jij misschien hoe dat komt?

Hm, bij mij werkt het nu wel. Soms duurt het even voordat hij (opnieuw) geladen is. Als je een vinkje ziet rechts van de commit, dan zou het in principe moeten werken. 
![afbeelding](https://github.com/user-attachments/assets/a3e6dca2-4762-4353-837f-514d53e1fd6a)

2024-08-09 16:35 UTC, webredactie-algoritmekader reviewed
@BartdeVisser: Dit is mijn voorzet voor de inkoop-tekst. Kun je je er zo in vinden? 

@Ruth: Het is de bedoeling dat we in de uitklappers opsommingen met linkjes zien. In de raketloze preview-functie zie ik die wel, maar in de preview-functie met het raketje lijkt het een rommeltje. Volgens Nout klopt de code, dus hopelijk ligt het aan mijn browser of zo ... Sowieso moet je hier denk ik nog geautomatiseerde linkjes plaatsen? Thnkz!

2024-08-12 07:36 UTC, BartdeVisser requested changes

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
> -## Vereisten
Waarom is dit kopje met deze informatie weggehaald? Dit is een afspraak die we hebben gemaakt wat betreft structuur. Suggestie/voorstel?

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
> -## Maatregelen
Idem

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
> -## Bruikbare informatie en bronnen
Ik wil dit kopje met de informatie hier graag nog even houden. Dit zou t.z.t. overbodig moeten worden als de maatregelen laag beter is uitgewerkt/wordt gepresenteerd aan de gebruikers. Reden, inkoopadviseurs vragen actief om voorbeelden van contractvoorwaarden. Het zit ook verwerkt in de maatregelen laag, maar dat is nog wat lastig te vinden (totdat we met de filters goed kunnen werken schat ik zo).

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
> -[Europese modelcontractbepalingen AI-systemen (hoog risico)](https://public-buyers-community.ec.europa.eu/sites/default/files/2023-10/AI_Procurement_Clauses_template_High_Risk%20NL.pdf)
Behouden

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
> -[Europese modelcontractbepalingen AI-systemen (niet hoog risico)](https://public-buyers-community.ec.europa.eu/sites/default/files/2023-10/AI_Procurement_Clauses_Template_NON_HIGH_RISK_NL.pdf)
Behouden

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
> -[Contractvoorwaarden voor algoritmen gemeente Amsterdam](https://www.amsterdam.nl/innovatie/digitalisering-technologie/algoritmen-ai/contractvoorwaarden-algoritmen/)
Behouden

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
> +- [Werkgroep Publieke Inkoop van algoritmen en AI – Algoritmekader](https://algoritmes.pleio.nl/groups/): besloten werkgroep voor het verbeteren van de informatie over publieke inkoop op deze website
Geen referentie maken naar de Werkgroep in het Algoritmekader zelf. Kennisdelen gaat niet via de Werkgroep, maar via Github/Team Algoritmekader. Ook in lijn met onderstaande.

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
> +In de [levenscyclus](https://minbzk.github.io/Algoritmekader/levenscyclus/) vind je de eisen voor opdrachtgevers en leveranciers in elke fase van het project.
```suggestion
In de [levenscyclus](https://minbzk.github.io/Algoritmekader/levenscyclus/) vind je de eisen voor opdrachtgevers en leveranciers in elke fase van de ontwikkeling van een algoritme.
```

2024-08-12 07:36 UTC, BartdeVisser commented on docs/bouwblokken/publieke-inkoop/index.md
>  title: Publieke inkoop
Algemene feedback:
In de Preview zie ik dat de site er een stuk 'cleaner' uit ziet. Dat is mooi! Toch ook wel een kritische kanttekening erbij. 

De informatieve stukken waarvan ik weet/heb getoetst bij de doelgroep dat het relevante passages zijn, zijn nagenoeg allemaal verloren gegaan. Het is nu geen verbindend schrijven meer van de relevante elementen. Ik zet dus mij vraagtekens bij of het nu nog informatief is en meer inzichten aanreikt dan lezers al hadden.

Daarbij natuurlijk ook het inzicht/erkenning dat hetgeen er stond bondiger kan worden beschreven. Ik heb alleen het gevoel er niet is herschreven maar enkel gestreept. De tekst die er stond is ook getoetst bij de Werkgroep waar zij inhoudelijk achter staan. 

Volgens mij verschillen de belevingen hiervoor nog wat teveel om verwerkt te krijgen in deze release en moeten we koersen op de volgende release.

2024-11-26 09:03 UTC, noutvandeijck commented
De teksten hier zijn verouderd, en er volgen nieuwe wijzigingen.

2024-11-26 09:03 UTC, closed without merging