Add extra page with integrated decision tree
MinBZK/Algoritmekader pull request #251
Opened 2024-09-03 08:11 UTC by laurensWe

## Beschrijf jouw aanpassingen

Extra tab to include the decision tree of https://github.com/MinBZK/AI-act-beslisboom into the AlgoritmeKader mkdocs through unpkg. New versions needs to be manually commited to this repository, the releases on the end of the beslisboom also needs to be triggered by building a release.

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader.

2024-09-03 08:13 UTC, laurensWe commented
<img width="1289" alt="image" src="https://github.com/user-attachments/assets/3c65604f-8c14-4ad0-9b8a-d2fbd043da3f">

2024-09-12 09:50 UTC, ruthkoole commented on docs/beslisboomaiact/index.md
> +title: Beslisboom AI Act
```suggestion
title: Beslisboom AI-verordening
```

2024-09-12 09:51 UTC, ruthkoole commented on docs/beslisboomaiact/index.md
> +# Beslisboom AI Act
```suggestion
# Beslisboom AI-verordening
```

2024-09-16 07:28 UTC, ruthkoole requested changes

2024-09-16 07:28 UTC, ruthkoole commented on docs/index.md
Dit zorgt voor een overwrite van de homepagina van het hele Algoritmekader, zie https://minbzk.github.io/Algoritmekader/pr-preview/pr-251/

Daar staat nu de definitie lijst?

2024-09-18 08:11 UTC, laurensWe commented on docs/index.md
Willen we op de mainpage nog wel een verwijzing naar de beslisboom overigens? nu is het alleen een tapje

2024-09-26 09:19 UTC, laurensWe commented on docs/index.md
@ruthkoole?

2024-11-13 13:29 UTC, laurensWe commented
Solved by this #362

2024-11-13 13:29 UTC, closed without merging