Release v1.6/maatregelen data
MinBZK/Algoritmekader pull request #307
Opened 2024-10-04 10:32 UTC by ruthkoole

## Beschrijf jouw aanpassingen
- twee maatregelen toegevoegd die te relateren zijn aan het onderwerp data

## Bij welk issue hoort deze pull-request?

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader.

2024-10-31 11:12 UTC, jaap-vink commented
Aan deze pagina zou ik nog enkele instumenten toevoegen. O.a. de Nederlandse-Europese norm NEN-EN-ISO/IEC 8183 "Information technology - Artificial intelligence - Data life cycle framework", de  "Toolbox verantwoord datagebruik"(https://realisatieibds.nl/page/view/628d59dd-0755-4c20-8217-d3f26d9d8a5c/toolbox-voor-verantwoord-datagebruik),

ISO Norm ISO/IEC 5259 "Artificial intelligence - Data quality for analytics and machine learning (ML)"

2024-11-11 16:08 UTC, noutvandeijck requested changes
paar suggesties gedaan voor wat aanpassingen. O.a. aantal titels en links waren nog niet goed, en bij één maatregel stond een kopje maar zonder bijbehorende tekst.
Verder echt goede maatregelen! :)

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/3-dat-01-datakwaliteit.md
Ik miste hier een verwijzing naar de FAIR-principes. Dat zou misschien nog in de toelichting opgenomen kunnen worden, al is het maar een verwijzing. Dat gaat natuurlijk meer over of je erbij kan en het kan uitwisselen etc., maar dat zou je ook datakwaliteit kunnen noemen. Ik dacht dat we (obv werk van Norbert) al zoiets hadden, maar kon het nu nergens goed terugvinden (oh de ironie ghehe..).

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/3-dat-07-training-validatie-en-testdata.md
> +title: Train-, validatie- en testdata
Deze titel moet nog beter, bijv:
```suggestion
title: Gebruik bij machine learning technieken gescheiden train-, test- en validatiedata en houdt rekening met underfitting en overfitting.
```

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/3-dat-07-training-validatie-en-testdata.md
> +toelichting: Indien je gebruik maakt van machine learning technieken, maak een passende keuze voor gescheiden train-, test- en validatiedata en houdt hierbij rekening met underfittng en overfitting.
```suggestion
toelichting: Indien je gebruik maakt van machine learning technieken, maak een passende keuze voor gescheiden train-, test- en validatiedata en houdt hierbij rekening met underfitting en overfitting. 
```

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/3-dat-07-training-validatie-en-testdata.md
> +Indien je gebruik maakt van machine learning technieken, maak een passende keuze voor gescheiden train-, test- en validatiedata en houdt hierbij rekening met underfittng en overfitting.
```suggestion
Indien je gebruik maakt van machine learning technieken, maak een passende keuze voor gescheiden train-, test- en validatiedata en houdt hierbij rekening met underfitting en overfitting. 
```

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/3-dat-07-training-validatie-en-testdata.md
> +    De [kwaliteit](datakwaliteit.md) van deze dataset moet goed zijn en zo representatief mogelijk voor de doelpopulatie. Eventuele bias of vooroordelen in deze dataset kan door het trainen in het mo
```suggestion
    De [kwaliteit](3-dat-01-datakwaliteit.md) van deze dataset moet goed zijn en zo representatief mogelijk voor de doelpopulatie. Eventuele [bias](../onderwerpen/bias-en-non-discriminatie.md#verschillende-vormen-van-bias) of vooroordelen in deze dataset kan door het trainen in het model sluipen.
```

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/3-dat-07-training-validatie-en-testdata.md
> +### Hoe split ik mijn dataset?
Dit stuk mist nu nog. Verder echt heldere maatregel!

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/3-dat-08-eigenaarschap-data.md
> +title: Controle of eigenaarschap over de data
titel is nog niet goed nu, suggestie voor een titel:

```suggestion
title: Zorg dat je controle of eigenaarschap hebt over de data
```

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/3-dat-08-eigenaarschap-data.md
> +- van voldoende kwaliteit is
```suggestion
- van voldoende [kwaliteit](3-dat-01-datakwaliteit.md) is
```

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/7-mon-04-evalueer-bij-veranderingen-in-data.md
> +title: Veranderingen in de data
```suggestion
title: Monitor regelmatig op veranderingen in de data. Bij veranderingen evalueer je de prestaties en output van het algoritme.
```

2024-11-11 16:08 UTC, noutvandeijck commented on docs/maatregelen/7-mon-04-evalueer-bij-veranderingen-in-data.md
> +- de data van [voldoende kwaliteit is voor de beoogde toepassing](datakwaliteit.md)
```suggestion
- de data van [voldoende kwaliteit is voor de beoogde toepassing](3-dat-01-datakwaliteit.md)
```

2024-11-12 12:57 UTC, ruthkoole commented on docs/maatregelen/3-dat-07-training-validatie-en-testdata.md
> +### Hoe split ik mijn dataset?
```suggestion
```

2024-11-12 12:57 UTC, ruthkoole commented on docs/maatregelen/3-dat-07-training-validatie-en-testdata.md
> +#### Grootte van de drie datasets
```suggestion
### Grootte van de drie datasets
```

2024-11-12 12:58 UTC, ruthkoole commented on docs/maatregelen/3-dat-07-training-validatie-en-testdata.md
> +#### k-fold cross validation
```suggestion
### k-fold cross validation
```

2024-11-12 13:15 UTC, noutvandeijck commented
> Aan deze pagina zou ik nog enkele instumenten toevoegen. O.a. de Nederlandse-Europese norm NEN-EN-ISO/IEC 8183 "Information technology - Artificial intelligence - Data life cycle framework", de "Toolbox verantwoord datagebruik"(https://realisatieibds.nl/page/view/628d59dd-0755-4c20-8217-d3f26d9d8a5c/toolbox-voor-verantwoord-datagebruik),
> 
> ISO Norm ISO/IEC 5259 "Artificial intelligence - Data quality for analytics and machine learning (ML)"

Zie comment van Jaap hierboven, @ruthkoole wellicht kunnen er nog externe links naar deze normen en naar de toolbox van IBDS worden toegevoegd in de maatregel _datakwaliteit_ en dat over lifecycle framework aan de maatregel _evalueer bij veranderingen in data_? Als dat niet meer lukt, laat maar weten, dan kan ik het waarschijnlijk ook doen vanmiddag!

Of behouden we het nog even voor volgende release?

2024-11-12 15:15 UTC, ruthkoole commented
> > Aan deze pagina zou ik nog enkele instumenten toevoegen. O.a. de Nederlandse-Europese norm NEN-EN-ISO/IEC 8183 "Information technology - Artificial intelligence - Data life cycle framework", de "Toolbox verantwoord datagebruik"(https://realisatieibds.nl/page/view/628d59dd-0755-4c20-8217-d3f26d9d8a5c/toolbox-voor-verantwoord-datagebruik),
> > ISO Norm ISO/IEC 5259 "Artificial intelligence - Data quality for analytics and machine learning (ML)"
> 
> Zie comment van Jaap hierboven, @ruthkoole wellicht kunnen er nog externe links naar deze normen en naar de toolbox van IBDS worden toegevoegd in de maatregel _datakwaliteit_ en dat over lifecycle framework aan de maatregel _evalueer bij veranderingen in data_? Als dat niet meer lukt, laat maar weten, dan kan ik het waarschijnlijk ook doen vanmiddag!
> 
> Of behouden we het nog even voor volgende release?

De toolbox van de IBDS is in ieder geval opgenomen op de pagina over data, zie https://minbzk.github.io/Algoritmekader/pr-preview/pr-307/onderwerpen/data/#goed-databeheer-datagovernance-en-datamanagement. 

Laten we volgende release kijken hoe we de standaarden het beste kunnen verwerken.

2024-11-12 15:18 UTC, ruthkoole commented on docs/maatregelen/3-dat-01-datakwaliteit.md
Ik heb een zinnetje toegevoegd!

2024-11-12 15:26 UTC, noutvandeijck commented on docs/maatregelen/3-dat-08-eigenaarschap-data.md
> +Wanneer een algoritme ontwikkeld of ingekocht wordt, is het belangrijk om toegang tot de gebruikte data goed te regelen.
```suggestion
Wanneer een algoritme ontwikkeld of ingekocht wordt, is het belangrijk om [toegang tot de gebruikte data](3-dat-02-fair-data.md) goed te regelen.
```

2024-11-12 15:29 UTC, noutvandeijck commented on docs/maatregelen/7-mon-04-evalueer-bij-veranderingen-in-data.md
>  - of het algoritme nog [presteert in lijn met de vastgestelde doelen](functioneren_in_lijn_met_doeleinden.md)
```suggestion
- of het algoritme nog [presteert in lijn met de vastgestelde doelen](5-ver-01-functioneren-in-lijn-met-doeleinden.md)
```

2024-11-12 15:30 UTC, noutvandeijck approved these changes
Mooie maatregelen geworden! Helemaal goed nu volgens mij.

2024-11-12 15:31 UTC, merged