Relase v1.6/verwijder vereisten opverzoek
MinBZK/Algoritmekader pull request #312
Opened 2024-10-11 08:15 UTC by jaspervanderheide

## Beschrijf jouw aanpassingen
Verwijderen van twee vereisten die overlappen met het opstellen van technische documentatie. Naar mij mening kunnen we beter die vereiste versterken en benadrukken dat toezichthouders het kunnen opvragen, ipv dupliceren. Creëert hopelijk wat overzicht.

## Bij welk issue hoort deze pull-request?
#309

## Checklist before requesting a review
- [x] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [x] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [x] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [x] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader.

2024-10-11 09:00 UTC, ruthkoole requested changes

2024-10-11 09:00 UTC, ruthkoole commented on docs/vereisten/aia-06-technische-documentatie.md
Het verzoek tot documentatie geldt denk ik niet alleen voor de technische documentatie. Het geldt voor heel afdeling twee (dus artikel 8 t/m 15). We moeten die zin dan ook bij die vereisten toevoegen.

2024-10-11 09:46 UTC, jaspervanderheide commented on docs/vereisten/aia-06-technische-documentatie.md
De technische documentatie gaat om de verantwoording voor alle vereisten van die afdeling 2 (dus artikel 8 t/m 15). Dus die documentatie omvat al al die eisen. Ik weet niet of we dat allemaal willen dupliceren?

2024-10-15 07:07 UTC, ruthkoole commented on docs/vereisten/aia-06-technische-documentatie.md
Je hebt gelijk denk ik!

2024-10-15 07:08 UTC, ruthkoole approved these changes

2024-10-15 12:51 UTC, merged