Release v1.6/geautomatiseerde besluitvorming
MinBZK/Algoritmekader pull request #360
Opened 2024-11-13 08:52 UTC by BartdeVisser

## Beschrijf jouw aanpassingen

## Bij welk issue hoort deze pull-request?

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader.

2024-12-12 16:00 UTC, noutvandeijck requested changes
@BartdeVisser zie comments, misschien dat het lukt om nog een leesbaarheidsslag te doen op de verschillende begrippen?
Het eerste stuk van de toelichting is heel mooi en wordt de lezer mooi ingeleid!

2024-12-12 16:00 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/vereisten/avg-10-recht-op-niet-geautomatiseerde-besluitvorming.md
> +Overheidsorganisatie zijn vaak belast met de uitvoering wettelijke taken waarbij zij 'besluiten' moeten nemen, bijvoorbeeld als een burger vraagt om een uitkering, toeslag of een subsidie.
```suggestion
Overheidsorganisaties zijn vaak belast met de uitvoering van wettelijke taken waarbij zij 'besluiten' moeten nemen, bijvoorbeeld als een burger vraagt om een uitkering, toeslag of een subsidie.
```

2024-12-12 16:00 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/vereisten/avg-10-recht-op-niet-geautomatiseerde-besluitvorming.md
> +Elke vorm van een geautomatiseerde verwerking van persoonsgegevens waarbij aan de hand van persoonsgegevens bepaalde persoonlijke aspecten van een natuurlijke persoon worden geëvalueerd, met name met
Deze zin leest erg lastig. Kan dit misschien simpeler?

2024-12-12 16:00 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/vereisten/avg-10-recht-op-niet-geautomatiseerde-besluitvorming.md
> +Profilering is bijzonder gevolg. Volgens deze definitie gaat het om een verwerking door een computersysteem waarbij het systeem algemene aanname(s) toegepast in een concreet geval, door een individu
Ook deze zinnen vind ik erg lastig te lezen. Ook begint hij met een gek stukje: "Profilering is bijzonder gevolg." Die snap ik ook niet helemaal. Of is dit eigenlijk een tussenkopje zoals de anderen? Dan op aparte regel en een #### invoegen :)

2024-12-12 16:00 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/vereisten/avg-10-recht-op-niet-geautomatiseerde-besluitvorming.md
> +In de context van deze vereist het begrip 'besluit' naar art. 22 AVG, niet naar het bredere besluitbegrip uit artikel 1:3 Algemene wet bestuursrecht (Awb). Bedacht moet worden dat het in de context v
ook deze leest erg juridisch, vooral de eerste paar zinnen.

2024-12-12 16:00 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/vereisten/avg-10-recht-op-niet-geautomatiseerde-besluitvorming.md
> +### Begrippen
moet het tussenkopje Begrippen niet een stukje naar beneden, naar nét boven Profilering?

2024-12-12 16:00 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/vereisten/avg-10-recht-op-niet-geautomatiseerde-besluitvorming.md
In het eerste stuk van de toelichting wordt de lezer mooi meegenomen, heel duidelijk! 👌🏻

Vanaf Profilering en de uitleg van die begrippen leest het een stuk lastiger en juridischer. Daar kan misschien een leesbaarheids-slag overheen, want ik vind het zelf al lastig te lezen. Verder inhoudelijk ziet het er goed uit, maar ik vrees dat mensen dus halverwege de tekst wellicht afhaken...

2024-12-12 20:03 UTC, BartdeVisser commented on docs/voldoen-aan-wetten-en-regels/vereisten/avg-10-recht-op-niet-geautomatiseerde-besluitvorming.md
Hi Nout,

Dank! En terecht punt wat je maakt. Ik moet eerlijk bekennen dat dit ook echt een zwaar juridisch geladen onderwerp is. Ik heb al geprobeerd om zaken enorm te vereenvoudigen. Lees maar eens het advies van de Landsadvocaat of het rapport van de AP. 

Gezien de gevoeligheid van dit onderwerp probeer ik ook zo dicht mogelijk te blijven bij de uitleg die aan zaken wordt gegeven en zo min mogelijk zelf te interpreteren. Zeker als het gaat om uitleg van definities. 

Heb links en rechts nog wat aan de vereiste gesleuteld. Zou je er nog eens naar willen kijken en me vergeven dat het soms wat juridische technisch blijft?

2024-12-16 13:46 UTC, noutvandeijck approved these changes

2024-12-16 13:48 UTC, merged