Release v1.7/maatregelen transparantie
MinBZK/Algoritmekader pull request #416
Opened 2024-11-26 10:15 UTC by BartdeVisser

## Beschrijf jouw aanpassingen

Hi Nout,

Hier de PR voor de transparantie maatregelen. Ik heb veel moeten schaven aan informatie die er al was. Daarbij de maatregelen van TNO geprobeerd een plek te geven. Vond het al met al een taaie klus. Wees maar kritisch!

Terwijl ik zaken aan het uitzoeken was voor transparantie, heb ik zo nu en dan ook andere maatregelen aangevuld, bijvoorbeeld met een voorbeeld. Geprobeerd het afgebakend te houden, maar soms toch iets 'on the fly' meegenomen.

Groet,
Bart

## Bij welk issue hoort deze pull-request?

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader.

2024-12-02 18:54 UTC, noutvandeijck requested changes
Mooie maatregelen, en mooie voorbeelden ook al toegevoegd. Mijn comments zijn vooral suggesties op leesbaarheid die je meteen kunt doorvoeren. Niks heel groots volgens mij.

2024-12-02 18:54 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/6-imp-01-werkinstructies-gebruikers.md
> +Het is belangrijk dat gebruikers een werkinstructie ontvangen met informatie hoe zijn met het algoritme kunnen en moeten werken. Hierin worden zaken beschreven als:
```suggestion
Het is belangrijk dat gebruikers een werkinstructie ontvangen met informatie over hoe zij met het algoritme kunnen en moeten werken. Hierin worden zaken beschreven als:

```

2024-12-02 18:54 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/6-imp-01-werkinstructies-gebruikers.md
> +-	Welke protocollen er zijn als zich incidenten voordoen.
```suggestion
-	Op wat voor manier het algoritme ondersteunt bij het uitvoeren van (wettelijke) taken.
-	Wat de mogelijkheden en beperkingen zijn bij het gebruik van het algoritme.
-	Wat de impact is van het gebruik van het algoritme op de samenleving en individuen (denk aan [energieverbruik](7-mon-05-meten-milieu-impact) of dat een besluit met rechtsgevolgen wordt genomen).
-	Wat de risico's zijn die aan het gebruik verbonden zijn (bijv. (automation) bias, false positives/negatives).
-	Welke maatregelen zijn getroffen om deze risico's te beperken (bijv. [bias analyse](5-ver-02-biasanalyse), ['stopknop' ingebouwd](4-owk-02-stopzetten-gebruik), transparantie over de output).
-	Hoe de output van het algoritme moet worden geïnterpreteerd.
-	Hoe het werkproces kan worden uitgevoerd, zonder ondersteuning van het algoritme.
-	Welke protocollen er zijn als incidenten zich voordoen. 

```

2024-12-03 09:55 UTC, BartdeVisser reviewed
Alle suggesties overgenomen. Dank Nout!

2024-12-03 09:55 UTC, BartdeVisser commented on docs/voldoen-aan-wetten-en-regels/maatregelen/0-org-02-beleid_opstellen_inzet_algoritmes.md
> +Algoritmekader
```suggestion
```

2024-12-03 11:01 UTC, noutvandeijck approved these changes

2024-12-03 11:01 UTC, merged