Missende inklapbare vereisten toegevoegd
MinBZK/Algoritmekader pull request #528
Opened 2024-12-24 15:48 UTC by E-Lacle

## Beschrijf jouw aanpassingen
Een aantal maatregelen misten inklapbare vereisten.

## Bij welk issue hoort deze pull-request?
#526 

## Checklist before requesting a review
- [ ] Ik heb de [contributing guidelines](https://github.com/MinBZK/Algoritmekader/blob/main/CONTRIBUTING.md) van deze repository gelezen en gevolgd. 
- [ ] Ik heb mijn aanpassingen gecheckt op spelfouten.
- [ ] Als ik gebruik heb gemaakt van links, dan heb ik gecheckt of deze werken.
- [ ] Ik heb gebruik gemaakt van de templates en formats van het algoritmekader.

2025-01-14 10:01 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/6-imp-06-vermelding-in-privacyverklaring.md
> +- Algoritmekader
```suggestion
```

2025-01-14 10:20 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/0-org-02-beleid-opstellen-inzet-algoritmes.md
>  Heb je een voorbeeld of best practice, laat het ons weten via algoritmes@minbzk.nl
```suggestion
!!! example "Handreiking Algoritmen - Gemeente Amsterdam"
	
	_Dit voorbeeld heeft een aantal aanpassingen nodig voordat deze in uw organisatie te gebruiken is._ 

	Gemeente Amsterdam heeft een Handreiking Algoritmen ontwikkeld waarin de aanpak van en instrumenten
voor verantwoord algoritme­­gebruik in Amsterdam worden toegelicht. Denk aan governance voor verantwoorde toepassing van algoritmes, en contractvoorwaarden voor algoritmische toepassingen.
	
	Bron: [Handreiking Algoritmen](https://www.amsterdam.nl/innovatie/digitalisering-technologie/handreikingen-playbooks/) (Er zijn hier ook handreikingen te vinden over _Dataverzameling_ en _Digitale ongelijkheid_.
	

## Bronnen

Heb je een voorbeeld of best practice, laat het ons weten via [algoritmes@minbzk.nl](mailto:algoritmes@minbzk.nl).
```

2025-01-14 14:13 UTC, noutvandeijck requested changes
Hoi Elizardo, heb ernaar gekeken. Ondanks dat de titel van het PR anders doet vermoeden, zijn er in deze PR veel voorbeelden toegevoegd, nice! Zitten goede dingen tussen, en maakt het Algoritmekader bruikbaarder!

 Ook dank voor het toevoegen van de codes voor uitklapbare velden.

Heb nog veel suggesties gedaan. Veel kleine taal-dingetjes, maar ook af en toe zinnen weggehaald om de voorbeelden wat meer to-the-point te maken. Graag even doorlopen, maar in de meeste gevallen kun je de de suggesties gewoon aan een batch commit toevoegen. Vergeet dan aan het einde niet die in één keer te committen. laat me weten wanneer je dat hebt gedaan, en dan kan ik hem daarna approven!

Dank alvast :)

2025-01-14 14:13 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/6-imp-09-politiek-bestuurlijk-besluit.md
> +	_Dit voorbeeld kan ter inspiratie dienen voor hoe de maatregel toegepast kan worden._
```suggestion
```

2025-01-14 14:13 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/6-imp-09-politiek-bestuurlijk-besluit.md
> +    Het CBW heeft aan de hand van deze eind evaluatie bepaald dat Slimme Check niet verder ontwikkeld wordt. Dit is gepubliceerd op de website van Gemeente Amsterdam naast besluiten en nieuws rondom
```suggestion
    Het CBW heeft aan de hand van deze eindevaluatie bepaald dat Slimme Check niet verder ontwikkeld wordt. Dit is gepubliceerd op de website van Gemeente Amsterdam naast besluiten en nieuws rondom andere zaken.
```

2025-01-14 14:13 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/6-imp-11-proces-privacyrechten.md
>  	_Dit voorbeeld kan zonder veel aanpassingen in uw organisatie gebruikt worden._
```suggestion
```

2025-01-14 14:13 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/7-mon-01-backups-maken.md
> +	_Dit voorbeeld kan zonder veel aanpassingen in uw organisatie gebruikt worden._
```suggestion
```

2025-01-14 14:13 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/7-mon-01-backups-maken.md
> +    De informatie beveiligingsdienst van de Vereniging Nederlandse gemeenten heeft een handreiking back-up en herstel ontwikkeld. Hierin staat uitleg over de wetgeving rondom back-ups en het herstell
```suggestion
    De Informatiebeveiligingsdienst van de Vereniging Nederlandse Gemeenten (VNG) heeft een handreiking back-up en herstel ontwikkeld. Hierin staat uitleg over de wetgeving rondom back-ups en het herstellen van back-ups.
```

2025-01-14 14:13 UTC, noutvandeijck commented on docs/voldoen-aan-wetten-en-regels/maatregelen/7-mon-03-informatiebeveiligingsincidenten.md
> +	_Dit voorbeeld kan ter inspiratie dienen voor hoe de maatregel toegepast kan worden._
```suggestion
```

2025-01-14 14:24 UTC, E-Lacle commented
Hey Nout,

Daar kwam ik later ook achter inderdaad, toen ik de PR deed waren het alleen het inklappen. Het probleem was dat ik daarna perongeluk verder ben gaan pushen op dezelfde branch (dus hetzelfde PR).
Ik zal er volgende keer wat beter op letten ;)

Dankjewel voor het reviewen in ieder geval ik zal er zo even naar kijken!

Van: Nout van Deijck ***@***.***>
Verzonden: dinsdag 14 januari 2025 15:14
Aan: MinBZK/Algoritmekader ***@***.***>
CC: Laclé, Elizardo ***@***.***>; Author ***@***.***>
Onderwerp: Re: [MinBZK/Algoritmekader] Missende inklapbare vereisten toegevoegd (PR #528)


@noutvandeijck requested changes on this pull request.

Hoi Elizardo, heb ernaar gekeken. Ondanks dat de titel van het PR anders doet vermoeden, zijn er in deze PR veel voorbeelden toegevoegd, nice! Zitten goede dingen tussen, en maakt het Algoritmekader bruikbaarder!

Ook dank voor het toevoegen van de codes voor uitklapbare velden.

Heb nog veel suggesties gedaan. Veel kleine taal-dingetjes, maar ook af en toe zinnen weggehaald om de voorbeelden wat meer to-the-point te maken. Graag even doorlopen, maar in de meeste gevallen kun je de de suggesties gewoon aan een batch commit toevoegen. Vergeet dan aan het einde niet die in één keer te committen. laat me weten wanneer je dat hebt gedaan, en dan kan ik hem daarna approven!

Dank alvast :)

________________________________

In docs/voldoen-aan-wetten-en-regels/maatregelen/0-org-02-beleid-opstellen-inzet-algoritmes.md<https://github.com/MinBZK/Algoritmekader/pull/528#discussion_r1914578641>:

> @@ -59,8 +58,15 @@ Zonder duidelijk beleid over de inzet van algoritmes kan het gebeuren dat algori



 ## Voorbeelden



-- [Controle op algoritmes](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjJr-7HwtSJAxWN8rsIHaOPNmkQFnoECBQQAw&url=https%3A%2F%2Fassets.amsterdam.nl%2Fpublish%2Fpages%2F1053010%2Fhandreiking_algoritmen.pdf&usg=AOvVaw3xCc4gbijZmLQayb7o02Pf&opi=89978449)

-- ISO/IEC 42001: Artificial intelligence (AI) Management System

-- [Webpagina van gemeente Amsterdam over algoritmes](https://www.amsterdam.nl/innovatie/digitalisering-technologie/algoritmen-ai/algoritmen/).

+!!! example "Handreiking Algoritmen - Gemeente Amsterdam"

paar aanpassingen gedaan in de tekst: taalfoutjes, en zinnetje eraf en erbij hier en daar.

________________________________

In docs/voldoen-aan-wetten-en-regels/maatregelen/0-org-03-toepassen-risicobeheer.md<https://github.com/MinBZK/Algoritmekader/pull/528#discussion_r1914579877>:

> @@ -58,16 +58,20 @@ Risico's worden niet (tijdig) vastgesteld en adequaat geadresseerd en behandeld.

 !!! example "Ministerie van Economische Zaken: Gids AI-verordening"



     _Dit voorbeeld kan ter inspiratie dienen voor hoe de maatregel toegepast kan worden._

+

     Het ministerie van Economische Zaken (EZ) heeft een gids opgesteld voor de AI-verordening. Hierin worden vier stappen toegelicht: Risico, AI, Rol en Verplichtingen. Om een plan op te stellen moet er ook aan de verplichtingen voldaan worden, deze verplichtingen staan samengevat in deze gids vanaf pagina 11. Hier wordt dit voor zowel een aanbieder als gebruiksverantwoordelijke toegelicht.
⬇️ Suggested change

-    Het ministerie van Economische Zaken (EZ) heeft een gids opgesteld voor de AI-verordening. Hierin worden vier stappen toegelicht: Risico, AI, Rol en Verplichtingen. Om een plan op te stellen moet er ook aan de verplichtingen voldaan worden, deze verplichtingen staan samengevat in deze gids vanaf pagina 11. Hier wordt dit voor zowel een aanbieder als gebruiksverantwoordelijke toegelicht.

+    Het Ministerie van Economische Zaken (EZ) heeft een gids opgesteld voor de AI-verordening. Hierin worden vier stappen toegelicht: Risico, AI, Rol en Verplichtingen. Om een plan op te stellen moet er ook aan de verplichtingen voldaan worden, deze verplichtingen staan samengevat in deze gids vanaf pagina 11. Hier wordt dit voor zowel een aanbieder als gebruiksverantwoordelijke toegelicht.

________________________________

In docs/voldoen-aan-wetten-en-regels/maatregelen/0-org-03-toepassen-risicobeheer.md<https://github.com/MinBZK/Algoritmekader/pull/528#discussion_r1914580237>:

>  !!! example "Nationaal Cyber Security Centrum: Richtlijnen veilig software ontwikkelen"



     _Dit voorbeeld kan ter inspiratie dienen voor hoe de maatregel toegepast kan worden._

+

     Het Nationaal Cyber Security Centrum van het ministerie van Justitie en Veiligheid heeft een publicatie over het ontwikkelen van veilige software. Hierin staat beschreven hoe op beleidsmatig niveau beveiligingsrichtlijnen toegepast kunnen worden. Er wordt in Hoofdstuk B.03 'Risicomanagement' een duidelijk beeld geschetst van wat noodzakelijke maatregelen hiervoor zijn.
⬇️ Suggested change

-    Het Nationaal Cyber Security Centrum van het ministerie van Justitie en Veiligheid heeft een publicatie over het ontwikkelen van veilige software. Hierin staat beschreven hoe op beleidsmatig niveau beveiligingsrichtlijnen toegepast kunnen worden. Er wordt in Hoofdstuk B.03 'Risicomanagement' een duidelijk beeld geschetst van wat noodzakelijke maatregelen hiervoor zijn.

+    Het Nationaal Cyber Security Centrum van het Ministerie van Justitie en Veiligheid heeft een publicatie over het ontwikkelen van veilige software. Hierin staat beschreven hoe op beleidsmatig niveau beveiligingsrichtlijnen toegepast kunnen worden. Er wordt in Hoofdstuk B.03 'Risicomanagement' een duidelijk beeld geschetst van wat noodzakelijke maatregelen hiervoor zijn.

________________________________

In docs/voldoen-aan-wetten-en-regels/maatregelen/0-org-03-toepassen-risicobeheer.md<https://github.com/MinBZK/Algoritmekader/pull/528#discussion_r1914581159>:

>      Het Nationaal Cyber Security Centrum van het ministerie van Justitie en Veiligheid heeft een publicatie over het ontwikkelen van veilige software. Hierin staat beschreven hoe op beleidsmatig niveau beveiligingsrichtlijnen toegepast kunnen worden. Er wordt in Hoofdstuk B.03 'Risicomanagement' een duidelijk beeld geschetst van wat noodzakelijke maatregelen hiervoor zijn.

+

     Hier worden ook verschillende methodes voorgesteld voor de risico analyse. Maar omdat deze publicatie uit 2021 komt is bijvoorbeeld de NEN-ISO/IEC 27005:2011 niet maar van toepassing maar is deze vervangen door de versie uit 2024 ([NEN-ISO/IEC 27005:2024](https://www.nen.nl/nen-en-iso-iec-27005-2024-en-327805)).
⬇️ Suggested change

-    Hier worden ook verschillende methodes voorgesteld voor de risico analyse. Maar omdat deze publicatie uit 2021 komt is bijvoorbeeld de NEN-ISO/IEC 27005:2011 niet maar van toepassing maar is deze vervangen door de versie uit 2024 ([NEN-ISO/IEC 27005:2024](https://www.nen.nl/nen-en-iso-iec-27005-2024-en-327805)).

+    Hier worden ook verschillende methodes voorgesteld voor de risicoanalyse. Omdat deze publicatie uit 2021 komt is bijvoorbeeld de NEN-ISO/IEC 27005:2011 niet maar van toepassing maar is deze vervangen door de versie uit 2024 ([NEN-ISO/IEC 27005:2024](https://www.nen.nl/nen-en-iso-iec-27005-2024-en-327805)).

________________________________

In docs/voldoen-aan-wetten-en-regels/maatregelen/0-org-05-bestaande-governance.md<https://github.com/MinBZK/Algoritmekader/pull/528#discussion_r1914592687>:

>

+!!! example "Naam van overheid: Korte uitleg"

+

+       _Dit voorbeeld kan zonder veel aanpassingen in uw organisatie gebruikt worden._

+

+       Binnen het Ministerie van Binnenlandse Zaken en Koninkrijksrelaties (BZK) is een handreiking opgesteld om twee verschillende instrumenten goed samen te kunnen gebruiken; Data Protection Impact Assessment (DPIA) en Impact Assessment Mensenrechten en Algoritmes (IAMA).

+

+       Binnen deze handreiking wordt toegelicht wat overeenkomsten en verschillen tussen het IAMA en DPIA zijn. Daarnaast wordt aangegeven hoe deze gecombineerd kunnen worden. Het doel is om zo deze instrumenten op een efficiënte en gebruikersvriendelijke manier samen te kunnen gebruiken.

+

+       Br [...]

2025-01-22 09:28 UTC, noutvandeijck approved these changes
Volgens mij is hij nu goed!

2025-01-22 09:30 UTC, merged